export const DEFAULT_PARAMS = {
  consumerIncome: 50000,
  productionCost: 20,
  taxPerUnit: 0,
  demandElasticity: 1.0,
  supplyElasticity: 1.0,
  priceCeiling: null,
  priceFloor: null,
  importQuota: null,
  demandIntercept: 100,
  supplyIntercept: 10,
  demandSlope: 2,
  supplySlope: 1.5,
  enablePriceCeiling: false,
  enablePriceFloor: false,
  enableImportQuota: false,
  priceCeilingValue: 20,
  priceFloorValue: 40,
  importQuotaValue: 100,
}
